# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Landmarks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmarks
  pod 'Amplify'                             # required amplify dependency
  pod 'Amplify/Tools'                       # allows to cal amplify CLI from within XCode
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin' # support for Cognito user authentication
  pod 'AmplifyPlugins/AWSAPIPlugin'         # support for GraphQL API
  pod 'AmplifyPlugins/AWSS3StoragePlugin'   # support for Amazon S3 storage
end
