baseURL = "https://amplify-ios-workshop.go-aws.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amplify iOS Workshop"
theme = "hugo-theme-learn"
uglyurls = true
#googleAnalytics = "UA-151590472-1"
sectionPagesMenu = "main"

[markup.highlight]
codeFences = true

[markup.goldmark.renderer]
unsafe= true
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "Sébastien Stormacq"
description = "Amplify iOS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutstitle = true
disableInlineCopyToClipBoard = true
disableLandingPageButton = true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @sebsto"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=sebsto"
weight = 1

[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML"]
